#!/bin/sh
# Just a wrapper to call file-converter-script in x-terminal-emulator if it is available, else as a normal (bash) script
HERE="$(dirname "$(readlink -f "${0}")")"
if which x-terminal-emulator > /dev/null ; then
    x-terminal-emulator -e "$HERE"/file-converter-script.sh
elif which bash > /dev/null ; then
    bash -c "$HERE"/file-converter-script.sh
else
    # Will ask to install bash
    /bin/sh -c "$HERE"/file-converter-script.sh
fi
exit 0
